name: Updates packages number badge on README

on:
  push:
    branches: [ main ]

jobs:
  update_badge:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Count packages
        run: |
          # Counts all packages in /packages including installer.vm
          num_packages=$(ls packages | wc -l)
          echo "num_packages=$num_packages" >> $GITHUB_ENV
      - name: Update dynamic badge gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.REPO_TOKEN }}
          gistID: 0e28118f551692f3401ac669e1d6761d
          filename: packages_badge.svg
          label: packages
          message: ${{ env.num_packages }}
          color: blue
